FROM ariksa/custom-nginx
EXPOSE 80
RUN echo "<br>Student IDs: 204034482_203523006" >> /usr/share/nginx/html/index.html
RUN echo "<br>Server version: <b>version-1</b>" >> /usr/share/nginx/html/index.html
